---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
  namespace: local-dev
  labels:
    app: zomato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: zomato
          image: subratdevops/zomato:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-svc
  namespace: jenkins
spec:
  selector:
    app: zomato
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort